baseURL = 'https://solohab.com/'
languageCode = 'tr-tr'
defaultContentLanguage = 'tr'
title = 'SoloHab Destek Merkezi'

googleAnalytics = "G-5BSRWP41PJ"

[params]
  description = "SoloHab Pazaryeri Entegrasyonu Yardım Belgeleri"

[[menu.main]]
    name = "Giriş"
    url = "/"
    weight = 10
    identifier = "giris"

[[menu.main]]
    name = "Destek"
    url = "/destek/"
    weight = 20
    identifier = "destek"

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 30
    identifier = "blog"

[[menu.main]]
    name = "Araçlar"
    url = "/araclar/"
    weight = 40
    identifier = "araclar"

[[menu.main]]
    name = "Ücretler"
    url = "/price/"
    weight = 50
    identifier = "ucretler"

[[menu.main]]
    name = "Hakkında"
    url = "/about/"
    weight = 60
    identifier = "hakkinda"
